"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 2.2.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ibutsu_client
from ibutsu_client.model.login_token import LoginToken


class TestLoginToken(unittest.TestCase):
    """LoginToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginToken(self):
        """Test LoginToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
