"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestDashboard(unittest.TestCase):
    """Dashboard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDashboard(self):
        """Test Dashboard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Dashboard()


if __name__ == "__main__":
    unittest.main()
