"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest

from ibutsu_client.model.pagination import Pagination
from ibutsu_client.model.project import Project

globals()["Pagination"] = Pagination
globals()["Project"] = Project


class TestProjectList(unittest.TestCase):
    """ProjectList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectList(self):
        """Test ProjectList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectList()


if __name__ == "__main__":
    unittest.main()
