# coding: utf-8

"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 1.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ibutsu_client
from ibutsu_client.models.report_list import ReportList  # noqa: E501
from ibutsu_client.rest import ApiException

class TestReportList(unittest.TestCase):
    """ReportList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ibutsu_client.models.report_list.ReportList()  # noqa: E501
        if include_optional :
            return ReportList(
                reports = [
                    {"id":"c6188b3fa767f0c9baf3","filename":"myreport.zip","mimetype":"application/zip","url":"http://ibutsu/reports/download/myreport.zip","download_url":"http://ibutsu/reports/download/myreport.zip","view_url":"http://ibutsu/reports/view/myreport.zip","parameters":{"type":"dashboard","filter":"test_navigation","source":"iqe-jenkins"},"status":"done"}
                    ], 
                pagination = {"page":2,"pageSize":25,"totalPages":10,"totalItems":243}
            )
        else :
            return ReportList(
        )

    def testReportList(self):
        """Test ReportList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
