"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

import pytest
from pydantic import ValidationError

from ibutsu_client.models.create_token import CreateToken


class TestCreateToken:
    """CreateToken model tests"""

    def test_creation_empty(self):
        with pytest.raises(ValidationError):
            CreateToken()

    def test_creation_full(self):
        model = CreateToken(name="token1", expires="2023-12-31")
        assert model.name == "token1"
        assert model.expires == "2023-12-31"

    def test_to_dict(self):
        model = CreateToken(name="token1", expires="2023-12-31")
        d = model.to_dict()
        assert d["name"] == "token1"

    def test_to_json(self):
        model = CreateToken(name="token1", expires="2023-12-31")
        j = model.to_json()
        data = json.loads(j)
        assert data["name"] == "token1"

    def test_from_dict(self):
        d = {"name": "token1", "expires": "2023-12-31"}
        model = CreateToken.from_dict(d)
        assert model.name == "token1"

    def test_from_json(self):
        j = '{"name": "token1", "expires": "2023-12-31"}'
        model = CreateToken.from_json(j)
        assert model.name == "token1"

    def test_to_str(self):
        model = CreateToken(name="token1", expires="2023-12-31")
        assert "token1" in model.to_str()

    def test_from_dict_none(self):
        assert CreateToken.from_dict(None) is None

    def test_from_dict_non_dict(self):
        orig = CreateToken(name="token1", expires="2023-12-31")
        model = CreateToken.from_dict(orig)
        assert model.name == "token1"

    def test_explicit_nones(self):
        # Assuming CreateToken handles explicit None for nullable fields
        model = CreateToken(name="token1", expires=None)
        d = model.to_dict()
        assert d["expires"] is None
