"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.7.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.run import Run


class TestRun(unittest.TestCase):
    """Run unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Run:
        """Test Run
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Run`
        """
        model = Run()
        if include_optional:
            return Run(
                id = '64c2ab9e-cd64-4815-bf73-83b00c2e650f',
                created = '2020-05-15T16:18:32.014053',
                duration = 154.778524555,
                source = 'my-tests',
                start_time = '2020-05-15T16:18:32.014053',
                component = 'login',
                env = 'qa',
                project_id = '44941c55-9736-42f6-acce-ca3c4739d0f3',
                summary = None,
                metadata = None
            )
        else:
            return Run(
        )
        """

    def testRun(self):
        """Test Run"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
