"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 2.2.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import ibutsu_client
from ibutsu_client.api.dashboard_api import DashboardApi  # noqa: E501


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self):
        self.api = DashboardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_dashboard(self):
        """Test case for add_dashboard

        Create a dashboard  # noqa: E501
        """
        pass

    def test_delete_dashboard(self):
        """Test case for delete_dashboard

        Delete a dashboard  # noqa: E501
        """
        pass

    def test_get_dashboard(self):
        """Test case for get_dashboard

        Get a single dashboard by ID  # noqa: E501
        """
        pass

    def test_get_dashboard_list(self):
        """Test case for get_dashboard_list

        Get a list of dashboards  # noqa: E501
        """
        pass

    def test_update_dashboard(self):
        """Test case for update_dashboard

        Update a dashboard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
