# coding: utf-8

"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 1.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ibutsu_client
from ibutsu_client.models.widget_param import WidgetParam  # noqa: E501
from ibutsu_client.rest import ApiException

class TestWidgetParam(unittest.TestCase):
    """WidgetParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WidgetParam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ibutsu_client.models.widget_param.WidgetParam()  # noqa: E501
        if include_optional :
            return WidgetParam(
                name = 'job_name', 
                description = 'The Jenkins job name', 
                type = 'string'
            )
        else :
            return WidgetParam(
        )

    def testWidgetParam(self):
        """Test WidgetParam"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
