"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_add_project(self) -> None:
        """Test case for add_project

        Create a project
        """

    def test_get_filter_params(self) -> None:
        """Test case for get_filter_params

        Get a project's filterable parameters
        """

    def test_get_project(self) -> None:
        """Test case for get_project

        Get a single project by ID
        """

    def test_get_project_list(self) -> None:
        """Test case for get_project_list

        Get a list of projects
        """

    def test_update_project(self) -> None:
        """Test case for update_project

        Update a project
        """


if __name__ == "__main__":
    unittest.main()
