"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.login_error import LoginError


class TestLoginError(unittest.TestCase):
    """LoginError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginError:
        """Test LoginError
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LoginError`
        """
        model = LoginError()
        if include_optional:
            return LoginError(
                code = 'ERR01',
                message = 'Username or password was invalid'
            )
        else:
            return LoginError(
        )
        """

    def testLoginError(self):
        """Test LoginError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
