"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestPagination(unittest.TestCase):
    """Pagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagination(self):
        """Test Pagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pagination()


if __name__ == "__main__":
    unittest.main()
