"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.7.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.token import Token


class TestToken(unittest.TestCase):
    """Token unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Token:
        """Test Token
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Token`
        """
        model = Token()
        if include_optional:
            return Token(
                id = 'e2772010-bc06-47ed-8b6b-767ab87427cc',
                user_id = '81e2c9d6-1593-4559-af4f-90f6f1f8fa03',
                name = 'My user token',
                expires = '2038-12-31T23:59:59+0000',
                token = '64ad787a-5aa8-48fa-842e-6e3b9631308a'
            )
        else:
            return Token(
                id = 'e2772010-bc06-47ed-8b6b-767ab87427cc',
                user_id = '81e2c9d6-1593-4559-af4f-90f6f1f8fa03',
                name = 'My user token',
                token = '64ad787a-5aa8-48fa-842e-6e3b9631308a',
        )
        """

    def testToken(self):
        """Test Token"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
