"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest

from ibutsu_client.api.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()

    def tearDown(self):
        pass

    def test_activate(self):
        """Test case for activate"""

    def test_auth(self):
        """Test case for auth"""

    def test_config(self):
        """Test case for config"""

    def test_login(self):
        """Test case for login"""

    def test_recover(self):
        """Test case for recover"""

    def test_register(self):
        """Test case for register"""

    def test_reset_password(self):
        """Test case for reset_password"""

    def test_support(self):
        """Test case for support"""


if __name__ == "__main__":
    unittest.main()
