# coding: utf-8

"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 1.10.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ibutsu_client
from ibutsu_client.models.run import Run  # noqa: E501
from ibutsu_client.rest import ApiException

class TestRun(unittest.TestCase):
    """Run unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Run
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ibutsu_client.models.run.Run()  # noqa: E501
        if include_optional :
            return Run(
                id = 'xBvhD1', 
                created = '2020-05-15T16:18:32.014053', 
                duration = 154.778524555, 
                source = 'my-tests', 
                start_time = '2020-05-15T16:18:32.014053', 
                summary = None, 
                metadata = None
            )
        else :
            return Run(
        )

    def testRun(self):
        """Test Run"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
