"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from uuid import uuid4

from ibutsu_client.models.artifact import Artifact


class TestArtifact:
    """Artifact model tests"""

    def test_artifact_creation_empty(self):
        """Test Artifact creation with no parameters"""
        artifact = Artifact()
        assert artifact.id is None
        assert artifact.filename is None

    def test_artifact_creation_full(self):
        """Test Artifact creation with all parameters"""
        artifact_id = uuid4()
        result_id = uuid4()
        run_id = uuid4()

        artifact = Artifact(
            id=artifact_id,
            result_id=result_id,
            run_id=run_id,
            filename="test_file.txt",
            additional_metadata={"size": 1024},
            upload_date="2023-01-01T12:00:00Z",
        )

        assert artifact.id == artifact_id
        assert artifact.result_id == result_id
        assert artifact.run_id == run_id
        assert artifact.filename == "test_file.txt"
        assert artifact.additional_metadata == {"size": 1024}

    def test_artifact_to_dict(self):
        """Test Artifact to_dict conversion"""
        artifact = Artifact(filename="dict_file.txt")
        artifact_dict = artifact.to_dict()

        assert isinstance(artifact_dict, dict)
        assert artifact_dict["filename"] == "dict_file.txt"

    def test_artifact_to_json(self):
        """Test Artifact to_json conversion"""
        artifact = Artifact(filename="json_file.txt")
        artifact_json = artifact.to_json()

        assert isinstance(artifact_json, str)
        parsed = json.loads(artifact_json)
        assert parsed["filename"] == "json_file.txt"

    def test_artifact_from_dict(self):
        """Test Artifact from_dict creation"""
        artifact_dict = {"filename": "from_dict.txt", "additional_metadata": {"key": "val"}}
        artifact = Artifact.from_dict(artifact_dict)

        assert isinstance(artifact, Artifact)
        assert artifact.filename == "from_dict.txt"
        assert artifact.additional_metadata == {"key": "val"}

    def test_artifact_from_json(self):
        """Test Artifact from_json creation"""
        artifact_json = '{"filename": "from_json.txt"}'
        artifact = Artifact.from_json(artifact_json)

        assert isinstance(artifact, Artifact)
        assert artifact.filename == "from_json.txt"

    def test_artifact_to_str(self):
        """Test Artifact to_str representation"""
        artifact = Artifact(filename="str_file.txt")
        artifact_str = artifact.to_str()

        assert isinstance(artifact_str, str)
        assert "str_file.txt" in artifact_str

    def test_artifact_none_values_excluded(self):
        """Test that None values are excluded from dict"""
        artifact = Artifact(filename="none_file.txt")
        artifact_dict = artifact.to_dict()

        assert "filename" in artifact_dict
        assert "upload_date" not in artifact_dict

    def test_artifact_from_dict_none(self):
        """Test Artifact.from_dict with None returns None"""
        artifact = Artifact.from_dict(None)
        assert artifact is None

    def test_artifact_from_dict_non_dict(self):
        """Test from_dict with a non-dict object"""
        art_obj = Artifact(filename="test_obj")
        new_art = Artifact.from_dict(art_obj)
        assert new_art.filename == "test_obj"

    def test_artifact_roundtrip_json(self):
        """Test Artifact can be serialized and deserialized"""
        original = Artifact(filename="roundtrip.txt", result_id=uuid4())
        json_str = original.to_json()
        restored = Artifact.from_json(json_str)

        assert restored.filename == original.filename
        assert restored.result_id == original.result_id
