"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestArtifact(unittest.TestCase):
    """Artifact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtifact(self):
        """Test Artifact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Artifact()


if __name__ == "__main__":
    unittest.main()
