"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from ibutsu_client.api.group_api import GroupApi
from ibutsu_client.exceptions import NotFoundException, ServiceException
from ibutsu_client.models.group import Group
from ibutsu_client.models.group_list import GroupList
from test.utils import sample_group_data, sample_pagination_data


class TestGroupApi:
    """GroupApi comprehensive tests"""

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(name="engineering-team"), "status": 201}],
        indirect=True,
    )
    def test_add_group_success(self, mocker, create_mock_response):
        """Test case for add_group - successfully create a new group"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group = Group(name="engineering-team")
        result = api.add_group(group=group)

        assert isinstance(result, Group)
        assert result.name == "engineering-team"
        api.api_client.call_api.assert_called_once()

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "unauthorized"}, "status": 401}],
        indirect=True,
    )
    def test_add_group_unauthorized(self, mocker, create_mock_response):
        """Test case for add_group without proper authentication"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group = Group(name="test-group")
        with pytest.raises((ServiceException, Exception)):
            api.add_group(group=group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "group already exists"}, "status": 409}],
        indirect=True,
    )
    def test_add_group_conflict(self, mocker, create_mock_response):
        """Test case for add_group with existing group name"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group = Group(name="existing-group")
        with pytest.raises((ServiceException, Exception)):
            api.add_group(group=group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(name="new-team"), "status": 201}],
        indirect=True,
    )
    def test_add_group_with_http_info(self, mocker, create_mock_response):
        """Test case for add_group_with_http_info"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group = Group(name="new-team")
        result = api.add_group_with_http_info(group=group)

        assert result.status_code == 201
        assert isinstance(result.data, Group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(name="qa-team"), "status": 200}],
        indirect=True,
    )
    def test_get_group_success(self, mocker, create_mock_response):
        """Test case for get_group - retrieve a single group"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_group(id=group_id)

        assert isinstance(result, Group)
        assert result.name == "qa-team"

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "not found"}, "status": 404}],
        indirect=True,
    )
    def test_get_group_not_found(self, mocker, create_mock_response):
        """Test case for get_group with non-existent group"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(NotFoundException):
            api.get_group(id=group_id)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(), "status": 200}],
        indirect=True,
    )
    def test_get_group_with_http_info(self, mocker, create_mock_response):
        """Test case for get_group_with_http_info"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_group_with_http_info(id=group_id)

        assert result.status_code == 200
        assert isinstance(result.data, Group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "groups": [
                        sample_group_data(name="team-alpha"),
                        sample_group_data(name="team-beta"),
                    ],
                    "pagination": sample_pagination_data(total_items=2),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_group_list_success(self, mocker, create_mock_response):
        """Test case for get_group_list - retrieve list of groups"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_group_list()

        assert isinstance(result, GroupList)
        assert len(result.groups) == 2

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "groups": [sample_group_data()],
                    "pagination": sample_pagination_data(page=2, page_size=10),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_group_list_with_pagination(self, mocker, create_mock_response):
        """Test case for get_group_list with pagination parameters"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_group_list(page=2, page_size=10)

        assert isinstance(result, GroupList)
        api.api_client.call_api.assert_called_once()

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "groups": [],
                    "pagination": sample_pagination_data(total_items=0),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_group_list_empty(self, mocker, create_mock_response):
        """Test case for get_group_list with no groups"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_group_list()

        assert isinstance(result, GroupList)
        assert len(result.groups) == 0

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "groups": [],
                    "pagination": sample_pagination_data(),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_group_list_with_http_info(self, mocker, create_mock_response):
        """Test case for get_group_list_with_http_info"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_group_list_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, GroupList)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(name="updated-team-name"), "status": 200}],
        indirect=True,
    )
    def test_update_group_success(self, mocker, create_mock_response):
        """Test case for update_group - successfully update a group"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        group = Group(name="updated-team-name")
        result = api.update_group(id=group_id, group=group)

        assert isinstance(result, Group)
        assert result.name == "updated-team-name"

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "not found"}, "status": 404}],
        indirect=True,
    )
    def test_update_group_not_found(self, mocker, create_mock_response):
        """Test case for update_group with non-existent group"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        group = Group(name="test-group")
        with pytest.raises(NotFoundException):
            api.update_group(id=group_id, group=group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_group_data(), "status": 200}],
        indirect=True,
    )
    def test_update_group_with_http_info(self, mocker, create_mock_response):
        """Test case for update_group_with_http_info"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        group = Group(name="test-group")
        result = api.update_group_with_http_info(id=group_id, group=group)

        assert result.status_code == 200
        assert isinstance(result.data, Group)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "internal error"}, "status": 500}],
        indirect=True,
    )
    def test_update_group_server_error(self, mocker, create_mock_response):
        """Test case for update_group with server error"""
        api = GroupApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        group_id = "550e8400-e29b-41d4-a716-446655440000"
        group = Group(name="test-group")
        with pytest.raises(ServiceException):
            api.update_group(id=group_id, group=group)
