"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.group_list import GroupList


class TestGroupList(unittest.TestCase):
    """GroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupList:
        """Test GroupList
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GroupList`
        """
        model = GroupList()
        if include_optional:
            return GroupList(
                groups = [
                    {"id":"a16ad60e-bf23-4195-99dc-594858ad3e5e","name":"Example group"}
                    ],
                pagination = {"page":2,"pageSize":25,"totalPages":10,"totalItems":243}
            )
        else:
            return GroupList(
        )
        """

    def testGroupList(self):
        """Test GroupList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
