"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.account_recovery import AccountRecovery


class TestAccountRecovery(unittest.TestCase):
    """AccountRecovery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountRecovery:
        """Test AccountRecovery
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountRecovery`
        """
        model = AccountRecovery()
        if include_optional:
            return AccountRecovery(
                email = 'user@domain.com'
            )
        else:
            return AccountRecovery(
                email = 'user@domain.com',
        )
        """

    def testAccountRecovery(self):
        """Test AccountRecovery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
