"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.artifact_list import ArtifactList


class TestArtifactList(unittest.TestCase):
    """ArtifactList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArtifactList:
        """Test ArtifactList
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ArtifactList`
        """
        model = ArtifactList()
        if include_optional:
            return ArtifactList(
                artifacts = [
                    {"filename":"filename","result_id":"a16ad60e-bf23-4195-99dc-594858ad3e5e","id":"22785097-a256-4aad-874b-9c204caba341","additional_metadata":{"key":"{}"},"upload_date":"2021-03-08T14:48:51+00:00"}
                    ],
                pagination = {"page":2,"pageSize":25,"totalPages":10,"totalItems":243}
            )
        else:
            return ArtifactList(
        )
        """

    def testArtifactList(self):
        """Test ArtifactList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
