"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_get_database_health(self) -> None:
        """Test case for get_database_health

        Get a health report for the database
        """

    def test_get_health(self) -> None:
        """Test case for get_health

        Get a general health report
        """

    def test_get_health_info(self) -> None:
        """Test case for get_health_info

        Get information about the server
        """


if __name__ == "__main__":
    unittest.main()
