"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestAccountRecovery(unittest.TestCase):
    """AccountRecovery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountRecovery(self):
        """Test AccountRecovery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountRecovery()


if __name__ == "__main__":
    unittest.main()
