"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from uuid import uuid4

from ibutsu_client.models.artifact import Artifact
from ibutsu_client.models.artifact_list import ArtifactList
from ibutsu_client.models.pagination import Pagination


class TestArtifactList:
    """ArtifactList model tests"""

    def test_artifact_list_creation_empty(self):
        """Test ArtifactList creation with no parameters"""
        artifact_list = ArtifactList()
        assert artifact_list.artifacts is None
        assert artifact_list.pagination is None

    def test_artifact_list_creation_full(self):
        """Test ArtifactList creation with all parameters"""
        artifact = Artifact(filename="test.txt")
        pagination = Pagination(page=1, page_size=10)

        artifact_list = ArtifactList(artifacts=[artifact], pagination=pagination)

        assert len(artifact_list.artifacts) == 1
        assert artifact_list.artifacts[0].filename == "test.txt"
        assert artifact_list.pagination.page == 1

    def test_artifact_list_to_dict(self):
        """Test ArtifactList to_dict conversion"""
        artifact = Artifact(filename="dict.txt")
        pagination = Pagination(page=1)
        artifact_list = ArtifactList(artifacts=[artifact], pagination=pagination)

        artifact_list_dict = artifact_list.to_dict()

        assert isinstance(artifact_list_dict, dict)
        assert "artifacts" in artifact_list_dict
        assert len(artifact_list_dict["artifacts"]) == 1
        assert artifact_list_dict["artifacts"][0]["filename"] == "dict.txt"
        assert "pagination" in artifact_list_dict
        assert artifact_list_dict["pagination"]["page"] == 1

    def test_artifact_list_to_json(self):
        """Test ArtifactList to_json conversion"""
        artifact = Artifact(filename="json.txt")
        artifact_list = ArtifactList(artifacts=[artifact])
        artifact_list_json = artifact_list.to_json()

        assert isinstance(artifact_list_json, str)
        parsed = json.loads(artifact_list_json)
        assert len(parsed["artifacts"]) == 1
        assert parsed["artifacts"][0]["filename"] == "json.txt"

    def test_artifact_list_from_dict(self):
        """Test ArtifactList from_dict creation"""
        artifact_dict = {"filename": "from_dict.txt"}
        pagination_dict = {"page": 2}
        list_dict = {"artifacts": [artifact_dict], "pagination": pagination_dict}

        artifact_list = ArtifactList.from_dict(list_dict)

        assert isinstance(artifact_list, ArtifactList)
        assert len(artifact_list.artifacts) == 1
        assert isinstance(artifact_list.artifacts[0], Artifact)
        assert artifact_list.artifacts[0].filename == "from_dict.txt"
        assert isinstance(artifact_list.pagination, Pagination)
        assert artifact_list.pagination.page == 2

    def test_artifact_list_from_json(self):
        """Test ArtifactList from_json creation"""
        json_str = '{"artifacts": [{"filename": "from_json.txt"}], "pagination": {"page": 3}}'
        artifact_list = ArtifactList.from_json(json_str)

        assert isinstance(artifact_list, ArtifactList)
        assert artifact_list.artifacts[0].filename == "from_json.txt"
        assert artifact_list.pagination.page == 3

    def test_artifact_list_to_str(self):
        """Test ArtifactList to_str representation"""
        artifact_list = ArtifactList()
        list_str = artifact_list.to_str()

        assert isinstance(list_str, str)

    def test_artifact_list_none_values_excluded(self):
        """Test that None values are excluded from dict"""
        artifact_list = ArtifactList(artifacts=[])
        list_dict = artifact_list.to_dict()

        assert "artifacts" in list_dict  # Empty list is not None
        assert "pagination" not in list_dict

    def test_artifact_list_from_dict_none(self):
        """Test ArtifactList.from_dict with None returns None"""
        artifact_list = ArtifactList.from_dict(None)
        assert artifact_list is None

    def test_artifact_list_from_dict_non_dict(self):
        """Test from_dict with a non-dict object"""
        # This might be tricky because from_dict has specific logic for artifacts list
        # But model_validate might handle it if the object has attributes matching fields
        # However, the custom from_dict in ArtifactList assumes obj is a dict (obj["artifacts"])
        # Let's check the code.
        # Code check:
        # if not isinstance(obj, dict):
        #     return cls.model_validate(obj)
        # So if not dict, it bypasses the manual list comprehension.
        # So testing this path is valid.

        artifact = Artifact(filename="test_obj")
        list_obj = ArtifactList(artifacts=[artifact])
        new_list = ArtifactList.from_dict(list_obj)
        assert len(new_list.artifacts) == 1
        assert new_list.artifacts[0].filename == "test_obj"

    def test_artifact_list_multiple_items(self):
        """Test ArtifactList to_dict with multiple items"""
        art1 = Artifact(filename="1.txt")
        art2 = Artifact(filename="2.txt")
        artifact_list = ArtifactList(artifacts=[art1, art2])

        list_dict = artifact_list.to_dict()
        assert len(list_dict["artifacts"]) == 2

    def test_artifact_list_roundtrip_json(self):
        """Test ArtifactList can be serialized and deserialized"""
        artifact = Artifact(filename="roundtrip.txt", result_id=uuid4())
        pagination = Pagination(page=1)
        original = ArtifactList(artifacts=[artifact], pagination=pagination)

        json_str = original.to_json()
        restored = ArtifactList.from_json(json_str)

        assert restored.artifacts[0].filename == original.artifacts[0].filename
        assert restored.pagination.page == original.pagination.page
