"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestLoginToken(unittest.TestCase):
    """LoginToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginToken(self):
        """Test LoginToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginToken()


if __name__ == "__main__":
    unittest.main()
