"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.group_api import GroupApi


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupApi()

    def tearDown(self) -> None:
        pass

    def test_add_group(self) -> None:
        """Test case for add_group

        Create a new group
        """

    def test_get_group(self) -> None:
        """Test case for get_group

        Get a group
        """

    def test_get_group_list(self) -> None:
        """Test case for get_group_list

        Get a list of groups
        """

    def test_update_group(self) -> None:
        """Test case for update_group

        Update a group
        """


if __name__ == "__main__":
    unittest.main()
