"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from ibutsu_client.models.login_error import LoginError


class TestLoginError:
    """LoginError model tests"""

    def test_creation_empty(self):
        model = LoginError()
        assert model.message is None

    def test_creation_full(self):
        model = LoginError(message="err", code="404")
        assert model.message == "err"
        assert model.code == "404"

    def test_to_dict(self):
        model = LoginError(message="err")
        d = model.to_dict()
        assert d["message"] == "err"

    def test_to_json(self):
        model = LoginError(message="err")
        j = model.to_json()
        data = json.loads(j)
        assert data["message"] == "err"

    def test_from_dict(self):
        d = {"message": "err"}
        model = LoginError.from_dict(d)
        assert model.message == "err"

    def test_from_json(self):
        j = '{"message": "err"}'
        model = LoginError.from_json(j)
        assert model.message == "err"

    def test_to_str(self):
        model = LoginError(message="err")
        assert "err" in model.to_str()

    def test_from_dict_none(self):
        assert LoginError.from_dict(None) is None

    def test_from_dict_non_dict(self):
        orig = LoginError(message="err")
        model = LoginError.from_dict(orig)
        assert model.message == "err"

    def test_none_values_excluded(self):
        model = LoginError(message="err")
        d = model.to_dict()
        assert "message" in d
        assert "code" not in d
