"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest

from ibutsu_client.model.pagination import Pagination
from ibutsu_client.model.report import Report

globals()["Pagination"] = Pagination
globals()["Report"] = Report


class TestReportList(unittest.TestCase):
    """ReportList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportList(self):
        """Test ReportList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReportList()


if __name__ == "__main__":
    unittest.main()
