"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from ibutsu_client.models.widget_param import WidgetParam
from ibutsu_client.models.widget_type import WidgetType


class TestWidgetType:
    """WidgetType model tests"""

    def test_widget_type_creation_empty(self):
        """Test WidgetType creation with no parameters"""
        widget_type = WidgetType()
        assert widget_type.id is None

    def test_widget_type_creation_full(self):
        """Test WidgetType creation with all parameters"""
        param = WidgetParam(name="p1")

        widget_type = WidgetType(
            id="wt1", title="Widget Type 1", description="Desc", params=[param], type="view"
        )

        assert widget_type.id == "wt1"
        assert widget_type.title == "Widget Type 1"
        assert len(widget_type.params) == 1
        assert widget_type.params[0].name == "p1"

    def test_widget_type_to_dict(self):
        """Test WidgetType to_dict conversion"""
        param = WidgetParam(name="p_dict")
        widget_type = WidgetType(id="wt_dict", params=[param])
        type_dict = widget_type.to_dict()

        assert isinstance(type_dict, dict)
        assert type_dict["id"] == "wt_dict"
        assert len(type_dict["params"]) == 1
        assert type_dict["params"][0]["name"] == "p_dict"

    def test_widget_type_to_json(self):
        """Test WidgetType to_json conversion"""
        widget_type = WidgetType(id="wt_json")
        type_json = widget_type.to_json()

        assert isinstance(type_json, str)
        parsed = json.loads(type_json)
        assert parsed["id"] == "wt_json"

    def test_widget_type_from_dict(self):
        """Test WidgetType from_dict creation"""
        param_dict = {"name": "p_from_dict"}
        type_dict = {"id": "wt_from_dict", "params": [param_dict]}
        widget_type = WidgetType.from_dict(type_dict)

        assert isinstance(widget_type, WidgetType)
        assert widget_type.id == "wt_from_dict"
        assert len(widget_type.params) == 1
        assert isinstance(widget_type.params[0], WidgetParam)
        assert widget_type.params[0].name == "p_from_dict"

    def test_widget_type_from_json(self):
        """Test WidgetType from_json creation"""
        type_json = '{"id": "wt_from_json", "params": [{"name": "p_json"}]}'
        widget_type = WidgetType.from_json(type_json)

        assert isinstance(widget_type, WidgetType)
        assert widget_type.id == "wt_from_json"
        assert widget_type.params[0].name == "p_json"

    def test_widget_type_to_str(self):
        """Test WidgetType to_str representation"""
        widget_type = WidgetType(id="wt_str")
        type_str = widget_type.to_str()

        assert isinstance(type_str, str)
        assert "wt_str" in type_str

    def test_widget_type_none_values_excluded(self):
        """Test that None values are excluded from dict"""
        widget_type = WidgetType(id="wt_none")
        type_dict = widget_type.to_dict()

        assert "id" in type_dict
        assert "title" not in type_dict

    def test_widget_type_from_dict_none(self):
        """Test WidgetType.from_dict with None returns None"""
        widget_type = WidgetType.from_dict(None)
        assert widget_type is None

    def test_widget_type_from_dict_non_dict(self):
        """Test from_dict with a non-dict object"""
        type_obj = WidgetType(id="test_obj")
        new_type = WidgetType.from_dict(type_obj)
        assert new_type.id == "test_obj"

    def test_widget_type_roundtrip_json(self):
        """Test WidgetType can be serialized and deserialized"""
        param = WidgetParam(name="p_roundtrip")
        original = WidgetType(id="wt_roundtrip", params=[param])
        json_str = original.to_json()
        restored = WidgetType.from_json(json_str)

        assert restored.id == original.id
        assert restored.params[0].name == original.params[0].name

    def test_widget_type_multiple_items(self):
        """Test WidgetType params list with multiple items"""
        p1 = WidgetParam(name="p1")
        p2 = WidgetParam(name="p2")
        widget_type = WidgetType(params=[p1, p2])

        type_dict = widget_type.to_dict()
        assert len(type_dict["params"]) == 2
