"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from ibutsu_client.models.login_support import LoginSupport


class TestLoginSupport:
    """LoginSupport model tests"""

    def test_creation_empty(self):
        model = LoginSupport()
        assert model.user is None

    def test_creation_full(self):
        model = LoginSupport(user=True, github=False)
        assert model.user is True
        assert model.github is False

    def test_to_dict(self):
        model = LoginSupport(user=True)
        d = model.to_dict()
        assert d["user"] is True

    def test_to_json(self):
        model = LoginSupport(user=True)
        j = model.to_json()
        data = json.loads(j)
        assert data["user"] is True

    def test_from_dict(self):
        d = {"user": True}
        model = LoginSupport.from_dict(d)
        assert model.user is True

    def test_from_json(self):
        j = '{"user": true}'
        model = LoginSupport.from_json(j)
        assert model.user is True

    def test_to_str(self):
        model = LoginSupport(user=True)
        assert "user" in model.to_str()

    def test_from_dict_none(self):
        assert LoginSupport.from_dict(None) is None

    def test_from_dict_non_dict(self):
        orig = LoginSupport(user=True)
        model = LoginSupport.from_dict(orig)
        assert model.user is True

    def test_none_values_excluded(self):
        model = LoginSupport(user=True)
        d = model.to_dict()
        assert "user" in d
        assert "google" not in d
