"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_get_task(self) -> None:
        """Test case for get_task

        Get the status or result of a task
        """


if __name__ == "__main__":
    unittest.main()
