"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest

from ibutsu_client.model.group import Group
from ibutsu_client.model.pagination import Pagination

globals()["Group"] = Group
globals()["Pagination"] = Pagination


class TestGroupList(unittest.TestCase):
    """GroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupList(self):
        """Test GroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupList()


if __name__ == "__main__":
    unittest.main()
