"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from uuid import uuid4

from ibutsu_client.models.pagination import Pagination
from ibutsu_client.models.widget_config import WidgetConfig
from ibutsu_client.models.widget_config_list import WidgetConfigList


class TestWidgetConfigList:
    """WidgetConfigList model tests"""

    def test_creation_empty(self):
        model = WidgetConfigList()
        assert model.widgets is None
        assert model.pagination is None

    def test_creation_full(self):
        item = WidgetConfig(title="w1")
        pagination = Pagination(page=1)
        model = WidgetConfigList(widgets=[item], pagination=pagination)
        assert len(model.widgets) == 1
        assert model.pagination.page == 1

    def test_to_dict(self):
        item = WidgetConfig(title="w1")
        model = WidgetConfigList(widgets=[item])
        data = model.to_dict()
        assert "widgets" in data
        assert len(data["widgets"]) == 1

    def test_to_dict_with_pagination(self):
        item = WidgetConfig(title="w1")
        pagination = Pagination(page=1)
        model = WidgetConfigList(widgets=[item], pagination=pagination)
        data = model.to_dict()
        assert "pagination" in data
        assert data["pagination"]["page"] == 1

    def test_to_json(self):
        item = WidgetConfig(title="w1")
        model = WidgetConfigList(widgets=[item])
        json_str = model.to_json()
        data = json.loads(json_str)
        assert len(data["widgets"]) == 1

    def test_from_dict(self):
        item_dict = {"title": "w1"}
        data = {"widgets": [item_dict], "pagination": {"page": 2}}
        model = WidgetConfigList.from_dict(data)
        assert len(model.widgets) == 1
        assert model.pagination.page == 2

    def test_from_json(self):
        json_str = '{"widgets": [{"title": "w1"}], "pagination": {"page": 3}}'
        model = WidgetConfigList.from_json(json_str)
        assert len(model.widgets) == 1

    def test_multiple_items(self):
        i1 = WidgetConfig(title="w1")
        i2 = WidgetConfig(title="w2")
        model = WidgetConfigList(widgets=[i1, i2])
        data = model.to_dict()
        assert len(data["widgets"]) == 2

    def test_roundtrip_json(self):
        item = WidgetConfig(title="w1", id=uuid4())
        original = WidgetConfigList(widgets=[item])
        json_str = original.to_json()
        restored = WidgetConfigList.from_json(json_str)
        assert len(restored.widgets) == 1
        assert restored.widgets[0].id == original.widgets[0].id

    def test_to_str(self):
        model = WidgetConfigList()
        s = model.to_str()
        assert isinstance(s, str)

    def test_from_dict_none(self):
        model = WidgetConfigList.from_dict(None)
        assert model is None

    def test_from_dict_non_dict(self):
        item = WidgetConfig(title="w1")
        orig = WidgetConfigList(widgets=[item])
        model = WidgetConfigList.from_dict(orig)
        assert len(model.widgets) == 1

    def test_list_none_values_excluded(self):
        model = WidgetConfigList(widgets=[])
        data = model.to_dict()
        assert "widgets" in data
        assert "pagination" not in data
