"""
Ibutsu API

A system to store and query test results  # noqa: E501

The version of the OpenAPI document: 2.3.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestWidgetConfig(unittest.TestCase):
    """WidgetConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWidgetConfig(self):
        """Test WidgetConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WidgetConfig()


if __name__ == "__main__":
    unittest.main()
