"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from ibutsu_client.api.widget_api import WidgetApi
from ibutsu_client.exceptions import NotFoundException, ServiceException
from ibutsu_client.models.widget_type_list import WidgetTypeList
from test.conftest import create_mock_response


class TestWidgetApi:
    """WidgetApi comprehensive tests"""

    def test_get_widget_success(self, mocker):
        """Test case for get_widget - successfully generate widget data"""
        api = WidgetApi()
        widget_data = {
            "type": "result-summary",
            "data": {
                "passed": 100,
                "failed": 5,
                "skipped": 2,
                "error": 0,
            },
        }
        mock_response = create_mock_response(widget_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_widget(id=widget_id)

        assert result is not None
        assert result["type"] == "result-summary"
        assert result["data"]["passed"] == 100
        api.api_client.call_api.assert_called_once()

    def test_get_widget_with_filters(self, mocker):
        """Test case for get_widget with filter parameters"""
        api = WidgetApi()
        widget_data = {
            "type": "jenkins-heatmap",
            "data": {"rows": [], "columns": []},
        }
        mock_response = create_mock_response(widget_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_widget(
            id=widget_id,
            params={"project": "test-project", "env": "production"},
        )

        assert result is not None
        assert result["type"] == "jenkins-heatmap"
        api.api_client.call_api.assert_called_once()

    def test_get_widget_with_additional_params(self, mocker):
        """Test case for get_widget with additional parameters"""
        api = WidgetApi()
        widget_data = {
            "type": "result-aggregation",
            "data": {"aggregations": []},
        }
        mock_response = create_mock_response(widget_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_widget(
            id=widget_id,
            params={"group_by": "component", "limit": 10},
        )

        assert result is not None
        api.api_client.call_api.assert_called_once()

    def test_get_widget_not_found(self, mocker):
        """Test case for get_widget with invalid widget name"""
        api = WidgetApi()
        mock_response = create_mock_response({"error": "widget not found"}, status=404)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(NotFoundException):
            api.get_widget(id=widget_id)

    def test_get_widget_server_error(self, mocker):
        """Test case for get_widget with server error"""
        api = WidgetApi()
        mock_response = create_mock_response({"error": "internal error"}, status=500)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(ServiceException):
            api.get_widget(id=widget_id)

    def test_get_widget_with_http_info(self, mocker):
        """Test case for get_widget_with_http_info"""
        api = WidgetApi()
        widget_data = {"type": "test-widget", "data": {}}
        mock_response = create_mock_response(widget_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        widget_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_widget_with_http_info(id=widget_id)

        assert result.status_code == 200
        assert result.data is not None

    def test_get_widget_types_success(self, mocker):
        """Test case for get_widget_types - retrieve list of available widget types"""
        api = WidgetApi()
        widget_types_data = {
            "types": [
                {
                    "name": "result-summary",
                    "description": "Summary of test results",
                    "params": [],
                },
                {
                    "name": "jenkins-heatmap",
                    "description": "Jenkins build heatmap",
                    "params": [],
                },
                {
                    "name": "result-aggregation",
                    "description": "Aggregated test results",
                    "params": [],
                },
            ]
        }
        mock_response = create_mock_response(widget_types_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_widget_types()

        assert isinstance(result, WidgetTypeList)
        assert len(result.types) == 3
        api.api_client.call_api.assert_called_once()

    def test_get_widget_types_empty(self, mocker):
        """Test case for get_widget_types with no types available"""
        api = WidgetApi()
        widget_types_data = {"types": []}
        mock_response = create_mock_response(widget_types_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_widget_types()

        assert isinstance(result, WidgetTypeList)
        assert len(result.types) == 0

    def test_get_widget_types_with_http_info(self, mocker):
        """Test case for get_widget_types_with_http_info"""
        api = WidgetApi()
        widget_types_data = {
            "types": [
                {
                    "name": "result-summary",
                    "description": "Summary",
                    "params": [],
                }
            ]
        }
        mock_response = create_mock_response(widget_types_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_widget_types_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, WidgetTypeList)

    def test_get_widget_types_server_error(self, mocker):
        """Test case for get_widget_types with server error"""
        api = WidgetApi()
        mock_response = create_mock_response({"error": "internal error"}, status=500)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        with pytest.raises(ServiceException):
            api.get_widget_types()
