"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from ibutsu_client.api.health_api import HealthApi
from ibutsu_client.exceptions import ServiceException
from ibutsu_client.models.health import Health
from ibutsu_client.models.health_info import HealthInfo
from test.conftest import create_mock_response


class TestHealthApi:
    """HealthApi unit tests"""

    def test_get_database_health(self, mocker):
        """Test case for get_database_health

        Get a health report for the database
        """
        # Mock response data
        response_data = {"status": "ok", "message": "Database is healthy"}

        # Create API instance
        api = HealthApi()

        # Mock the call_api method
        mock_response = create_mock_response(response_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        # Call the method
        result = api.get_database_health()

        # Verify the result
        assert isinstance(result, Health)
        assert result.status == "ok"
        assert result.message == "Database is healthy"

        # Verify call_api was called
        api.api_client.call_api.assert_called_once()

    def test_get_database_health_error(self, mocker):
        """Test case for get_database_health with error response"""
        response_data = {"status": "error", "message": "Database connection failed"}

        api = HealthApi()
        mock_response = create_mock_response(response_data, status=500)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        # 500 errors raise ServiceException
        with pytest.raises(ServiceException) as exc_info:
            api.get_database_health()

        assert exc_info.value.status == 500
        assert "error" in str(exc_info.value.body).lower()

    def test_get_health(self, mocker):
        """Test case for get_health

        Get a general health report
        """
        response_data = {"status": "ok", "message": "Service is healthy"}

        api = HealthApi()
        mock_response = create_mock_response(response_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_health()

        assert isinstance(result, Health)
        assert result.status == "ok"
        assert result.message == "Service is healthy"

    def test_get_health_info(self, mocker):
        """Test case for get_health_info

        Get information about the server
        """
        response_data = {
            "frontend": "https://ibutsu.example.com",
            "backend": "https://api.ibutsu.example.com",
            "api_ui": "https://api.ibutsu.example.com/docs",
        }

        api = HealthApi()
        mock_response = create_mock_response(response_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_health_info()

        assert isinstance(result, HealthInfo)
        assert result.frontend == "https://ibutsu.example.com"
        assert result.backend == "https://api.ibutsu.example.com"
        assert result.api_ui == "https://api.ibutsu.example.com/docs"

    def test_get_health_info_with_http_info(self, mocker):
        """Test case for get_health_info_with_http_info"""
        response_data = {
            "frontend": "https://ibutsu.example.com",
            "backend": "https://api.ibutsu.example.com",
            "api_ui": "https://api.ibutsu.example.com/docs",
        }

        api = HealthApi()
        mock_response = create_mock_response(response_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        result = api.get_health_info_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, HealthInfo)
        assert result.data.frontend == "https://ibutsu.example.com"
