"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 2.2.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ibutsu_client
from ibutsu_client.model.token import Token


class TestToken(unittest.TestCase):
    """Token unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToken(self):
        """Test Token"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Token()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
