"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.7.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoginApi()

    def tearDown(self) -> None:
        pass

    def test_activate(self) -> None:
        """Test case for activate"""

    def test_auth(self) -> None:
        """Test case for auth"""

    def test_config(self) -> None:
        """Test case for config"""

    def test_login(self) -> None:
        """Test case for login"""

    def test_recover(self) -> None:
        """Test case for recover"""

    def test_register(self) -> None:
        """Test case for register"""

    def test_reset_password(self) -> None:
        """Test case for reset_password"""

    def test_support(self) -> None:
        """Test case for support"""


if __name__ == "__main__":
    unittest.main()
