"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from ibutsu_client.api.user_api import UserApi
from ibutsu_client.exceptions import NotFoundException, ServiceException
from ibutsu_client.models.create_token import CreateToken
from ibutsu_client.models.token import Token
from ibutsu_client.models.token_list import TokenList
from ibutsu_client.models.user import User
from test.utils import sample_pagination_data, sample_token_data, sample_user_data


class TestUserApi:
    """UserApi comprehensive tests"""

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_token_data(name="api-token", expires="2025-12-31"), "status": 201}],
        indirect=True,
    )
    def test_add_token_success(self, mocker, create_mock_response):
        """Test case for add_token - successfully create a token"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        create_token = CreateToken(name="api-token", expires="2025-12-31")
        result = api.add_token(create_token=create_token)

        assert isinstance(result, Token)
        assert result.name == "api-token"
        assert result.expires == "2025-12-31"
        api.api_client.call_api.assert_called_once()

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "unauthorized"}, "status": 401}],
        indirect=True,
    )
    def test_add_token_unauthorized(self, mocker, create_mock_response):
        """Test case for add_token with no authentication"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        create_token = CreateToken(name="test-token", expires="2025-12-31")
        with pytest.raises((ServiceException, Exception)):  # Should raise unauthorized exception
            api.add_token(create_token=create_token)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_token_data(name="test-token"), "status": 201}],
        indirect=True,
    )
    def test_add_token_with_http_info(self, mocker, create_mock_response):
        """Test case for add_token_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        create_token = CreateToken(name="test-token", expires="2025-12-31")
        result = api.add_token_with_http_info(create_token=create_token)

        assert result.status_code == 201
        assert isinstance(result.data, Token)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {}, "status": 204}],
        indirect=True,
    )
    def test_delete_token_success(self, mocker, create_mock_response):
        """Test case for delete_token - successfully delete a token"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        api.delete_token(id=token_id)

        # 204 No Content typically returns None
        api.api_client.call_api.assert_called_once()

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "not found"}, "status": 404}],
        indirect=True,
    )
    def test_delete_token_not_found(self, mocker, create_mock_response):
        """Test case for delete_token with non-existent token"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(NotFoundException):
            api.delete_token(id=token_id)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {}, "status": 204}],
        indirect=True,
    )
    def test_delete_token_with_http_info(self, mocker, create_mock_response):
        """Test case for delete_token_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.delete_token_with_http_info(id=token_id)

        assert result.status_code == 204

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": sample_user_data(email="current@example.com", name="Current User"),
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_current_user_success(self, mocker, create_mock_response):
        """Test case for get_current_user - retrieve current user details"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_current_user()

        assert isinstance(result, User)
        assert result.email == "current@example.com"
        assert result.name == "Current User"

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "unauthorized"}, "status": 401}],
        indirect=True,
    )
    def test_get_current_user_unauthorized(self, mocker, create_mock_response):
        """Test case for get_current_user without authentication"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        with pytest.raises((ServiceException, Exception)):
            api.get_current_user()

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_user_data(), "status": 200}],
        indirect=True,
    )
    def test_get_current_user_with_http_info(self, mocker, create_mock_response):
        """Test case for get_current_user_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_current_user_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, User)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_token_data(name="specific-token"), "status": 200}],
        indirect=True,
    )
    def test_get_token_success(self, mocker, create_mock_response):
        """Test case for get_token - retrieve a single token"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_token(id=token_id)

        assert isinstance(result, Token)
        assert result.name == "specific-token"

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "not found"}, "status": 404}],
        indirect=True,
    )
    def test_get_token_not_found(self, mocker, create_mock_response):
        """Test case for get_token with non-existent token"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(NotFoundException):
            api.get_token(id=token_id)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_token_data(), "status": 200}],
        indirect=True,
    )
    def test_get_token_with_http_info(self, mocker, create_mock_response):
        """Test case for get_token_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        token_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_token_with_http_info(id=token_id)

        assert result.status_code == 200
        assert isinstance(result.data, Token)

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "tokens": [
                        sample_token_data(name="token1"),
                        sample_token_data(name="token2"),
                    ],
                    "pagination": sample_pagination_data(page=1, page_size=25, total_items=2),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_token_list_success(self, mocker, create_mock_response):
        """Test case for get_token_list - retrieve list of tokens"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_token_list()

        assert isinstance(result, TokenList)
        assert len(result.tokens) == 2

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "tokens": [sample_token_data()],
                    "pagination": sample_pagination_data(page=2, page_size=10),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_token_list_with_pagination(self, mocker, create_mock_response):
        """Test case for get_token_list with pagination parameters"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_token_list(page=2, page_size=10)

        assert isinstance(result, TokenList)
        api.api_client.call_api.assert_called_once()

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": {
                    "tokens": [],
                    "pagination": sample_pagination_data(),
                },
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_get_token_list_with_http_info(self, mocker, create_mock_response):
        """Test case for get_token_list_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.get_token_list_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, TokenList)

    @pytest.mark.parametrize(
        "create_mock_response",
        [
            {
                "data": sample_user_data(email="current@example.com", name="Current User"),
                "status": 200,
            }
        ],
        indirect=True,
    )
    def test_update_current_user_success(self, mocker, create_mock_response):
        """Test case for update_current_user - get current user details"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.update_current_user()

        assert isinstance(result, User)
        assert result.email == "current@example.com"
        assert result.name == "Current User"

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "unauthorized"}, "status": 401}],
        indirect=True,
    )
    def test_update_current_user_unauthorized(self, mocker, create_mock_response):
        """Test case for update_current_user without authentication"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        with pytest.raises((ServiceException, Exception)):
            api.update_current_user()

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": sample_user_data(), "status": 200}],
        indirect=True,
    )
    def test_update_current_user_with_http_info(self, mocker, create_mock_response):
        """Test case for update_current_user_with_http_info"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        result = api.update_current_user_with_http_info()

        assert result.status_code == 200
        assert isinstance(result.data, User)

    @pytest.mark.parametrize(
        "create_mock_response",
        [{"data": {"error": "internal error"}, "status": 500}],
        indirect=True,
    )
    def test_update_current_user_server_error(self, mocker, create_mock_response):
        """Test case for update_current_user with server error"""
        api = UserApi()
        mocker.patch.object(api.api_client, "call_api", return_value=create_mock_response)

        with pytest.raises(ServiceException):
            api.update_current_user()
