"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.widget_param import WidgetParam


class TestWidgetParam(unittest.TestCase):
    """WidgetParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WidgetParam:
        """Test WidgetParam
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WidgetParam`
        """
        model = WidgetParam()
        if include_optional:
            return WidgetParam(
                name = 'job_name',
                description = 'The Jenkins job name',
                type = 'string'
            )
        else:
            return WidgetParam(
        )
        """

    def testWidgetParam(self):
        """Test WidgetParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
