"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json
from uuid import uuid4

from ibutsu_client.models.project import Project


class TestProject:
    """Project model tests"""

    def test_project_creation_empty(self):
        """Test Project creation with no parameters"""
        project = Project()
        assert project.id is None
        assert project.name is None

    def test_project_creation_full(self):
        """Test Project creation with all parameters"""
        project_id = uuid4()
        owner_id = uuid4()
        group_id = uuid4()

        project = Project(
            id=project_id,
            name="my-project",
            title="My Project",
            owner_id=owner_id,
            group_id=group_id,
        )

        assert project.id == project_id
        assert project.name == "my-project"
        assert project.title == "My Project"
        assert project.owner_id == owner_id
        assert project.group_id == group_id

    def test_project_to_dict(self):
        """Test Project to_dict conversion"""
        project = Project(name="dict_project", title="Dict Project")
        project_dict = project.to_dict()

        assert isinstance(project_dict, dict)
        assert project_dict["name"] == "dict_project"
        assert project_dict["title"] == "Dict Project"

    def test_project_to_json(self):
        """Test Project to_json conversion"""
        project = Project(name="json_project")
        project_json = project.to_json()

        assert isinstance(project_json, str)
        parsed = json.loads(project_json)
        assert parsed["name"] == "json_project"

    def test_project_from_dict(self):
        """Test Project from_dict creation"""
        project_dict = {"name": "from_dict", "title": "From Dict"}
        project = Project.from_dict(project_dict)

        assert isinstance(project, Project)
        assert project.name == "from_dict"
        assert project.title == "From Dict"

    def test_project_from_json(self):
        """Test Project from_json creation"""
        project_json = '{"name": "from_json"}'
        project = Project.from_json(project_json)

        assert isinstance(project, Project)
        assert project.name == "from_json"

    def test_project_to_str(self):
        """Test Project to_str representation"""
        project = Project(name="str_project")
        project_str = project.to_str()

        assert isinstance(project_str, str)
        assert "str_project" in project_str

    def test_project_none_values_excluded(self):
        """Test that None values are excluded from dict"""
        project = Project(name="none_project")
        project_dict = project.to_dict()

        assert "name" in project_dict
        assert "title" not in project_dict

    def test_project_explicit_nones(self):
        """Test explicit None values are preserved in to_dict if set"""
        project = Project(owner_id=None, group_id=None)
        project_dict = project.to_dict()

        assert "owner_id" in project_dict
        assert project_dict["owner_id"] is None
        assert "group_id" in project_dict
        assert project_dict["group_id"] is None

    def test_project_from_dict_none(self):
        """Test Project.from_dict with None returns None"""
        project = Project.from_dict(None)
        assert project is None

    def test_project_from_dict_non_dict(self):
        """Test from_dict with a non-dict object"""
        proj_obj = Project(name="test_obj")
        new_proj = Project.from_dict(proj_obj)
        assert new_proj.name == "test_obj"

    def test_project_roundtrip_json(self):
        """Test Project can be serialized and deserialized"""
        original = Project(name="roundtrip", title="Roundtrip")
        json_str = original.to_json()
        restored = Project.from_json(json_str)

        assert restored.name == original.name
        assert restored.title == original.title
