"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from ibutsu_client.models.pagination import Pagination
from ibutsu_client.models.widget_type import WidgetType
from ibutsu_client.models.widget_type_list import WidgetTypeList


class TestWidgetTypeList:
    """WidgetTypeList model tests"""

    def test_creation_empty(self):
        model = WidgetTypeList()
        assert model.types is None
        assert model.pagination is None

    def test_creation_full(self):
        item = WidgetType(id="wt1")
        pagination = Pagination(page=1)
        model = WidgetTypeList(types=[item], pagination=pagination)
        assert len(model.types) == 1
        assert model.pagination.page == 1

    def test_to_dict(self):
        item = WidgetType(id="wt1")
        model = WidgetTypeList(types=[item])
        data = model.to_dict()
        assert "types" in data
        assert len(data["types"]) == 1

    def test_to_dict_with_pagination(self):
        item = WidgetType(id="wt1")
        pagination = Pagination(page=1)
        model = WidgetTypeList(types=[item], pagination=pagination)
        data = model.to_dict()
        assert "pagination" in data
        assert data["pagination"]["page"] == 1

    def test_to_json(self):
        item = WidgetType(id="wt1")
        model = WidgetTypeList(types=[item])
        json_str = model.to_json()
        data = json.loads(json_str)
        assert len(data["types"]) == 1

    def test_from_dict(self):
        item_dict = {"id": "wt1"}
        data = {"types": [item_dict], "pagination": {"page": 2}}
        model = WidgetTypeList.from_dict(data)
        assert len(model.types) == 1
        assert model.pagination.page == 2

    def test_from_json(self):
        json_str = '{"types": [{"id": "wt1"}], "pagination": {"page": 3}}'
        model = WidgetTypeList.from_json(json_str)
        assert len(model.types) == 1

    def test_multiple_items(self):
        i1 = WidgetType(id="wt1")
        i2 = WidgetType(id="wt2")
        model = WidgetTypeList(types=[i1, i2])
        data = model.to_dict()
        assert len(data["types"]) == 2

    def test_roundtrip_json(self):
        item = WidgetType(id="wt1", title="Type 1")
        original = WidgetTypeList(types=[item])
        json_str = original.to_json()
        restored = WidgetTypeList.from_json(json_str)
        assert len(restored.types) == 1
        assert restored.types[0].id == original.types[0].id

    def test_to_str(self):
        model = WidgetTypeList()
        s = model.to_str()
        assert isinstance(s, str)

    def test_from_dict_none(self):
        model = WidgetTypeList.from_dict(None)
        assert model is None

    def test_from_dict_non_dict(self):
        item = WidgetType(id="wt1")
        orig = WidgetTypeList(types=[item])
        model = WidgetTypeList.from_dict(orig)
        assert len(model.types) == 1

    def test_list_none_values_excluded(self):
        model = WidgetTypeList(types=[])
        data = model.to_dict()
        assert "types" in data
        assert "pagination" not in data
