"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.7.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.api.artifact_api import ArtifactApi


class TestArtifactApi(unittest.TestCase):
    """ArtifactApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtifactApi()

    def tearDown(self) -> None:
        pass

    def test_delete_artifact(self) -> None:
        """Test case for delete_artifact

        Delete an artifact
        """

    def test_download_artifact(self) -> None:
        """Test case for download_artifact

        Download an artifact
        """

    def test_get_artifact(self) -> None:
        """Test case for get_artifact

        Get a single artifact
        """

    def test_get_artifact_list(self) -> None:
        """Test case for get_artifact_list

        Get a (filtered) list of artifacts
        """

    def test_upload_artifact(self) -> None:
        """Test case for upload_artifact

        Uploads a test run artifact
        """

    def test_view_artifact(self) -> None:
        """Test case for view_artifact

        Stream an artifact directly to the client/browser
        """


if __name__ == "__main__":
    unittest.main()
