"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.8.3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from ibutsu_client.api.task_api import TaskApi
from ibutsu_client.exceptions import NotFoundException, ServiceException
from test.conftest import create_mock_response


class TestTaskApi:
    """TaskApi comprehensive tests"""

    def test_get_task_pending(self, mocker):
        """Test case for get_task with pending status"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "pending",
            "task_type": "export",
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result is not None
        assert result["status"] == "pending"
        assert result["task_type"] == "export"
        api.api_client.call_api.assert_called_once()

    def test_get_task_running(self, mocker):
        """Test case for get_task with running status"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "running",
            "task_type": "bulk_update",
            "progress": 45,
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result is not None
        assert result["status"] == "running"
        assert result["progress"] == 45

    def test_get_task_completed(self, mocker):
        """Test case for get_task with completed status"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "completed",
            "task_type": "export",
            "result": {
                "file_url": "https://example.com/exports/results.tar.gz",
                "file_size": 1024000,
            },
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result is not None
        assert result["status"] == "completed"
        assert result["result"]["file_url"] == "https://example.com/exports/results.tar.gz"

    def test_get_task_failed(self, mocker):
        """Test case for get_task with failed status"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "failed",
            "task_type": "bulk_update",
            "error": "Database connection timeout",
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result is not None
        assert result["status"] == "failed"
        assert result["error"] == "Database connection timeout"

    def test_get_task_not_found(self, mocker):
        """Test case for get_task with non-existent task"""
        api = TaskApi()
        mock_response = create_mock_response({"error": "task not found"}, status=404)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(NotFoundException):
            api.get_task(id=task_id)

    def test_get_task_with_http_info(self, mocker):
        """Test case for get_task_with_http_info"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "completed",
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task_with_http_info(id=task_id)

        assert result.status_code == 200
        assert result.data is not None

    def test_get_task_unauthorized(self, mocker):
        """Test case for get_task without authentication"""
        api = TaskApi()
        mock_response = create_mock_response({"error": "unauthorized"}, status=401)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises((ServiceException, Exception)):
            api.get_task(id=task_id)

    def test_get_task_server_error(self, mocker):
        """Test case for get_task with server error"""
        api = TaskApi()
        mock_response = create_mock_response({"error": "internal error"}, status=500)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        with pytest.raises(ServiceException):
            api.get_task(id=task_id)

    def test_get_task_export_type(self, mocker):
        """Test case for get_task with export task type"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "completed",
            "task_type": "export",
            "result": {
                "format": "json",
                "records_exported": 1000,
            },
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result["task_type"] == "export"
        assert result["result"]["records_exported"] == 1000

    def test_get_task_bulk_update_type(self, mocker):
        """Test case for get_task with bulk_update task type"""
        api = TaskApi()
        task_data = {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "status": "completed",
            "task_type": "bulk_update",
            "result": {
                "updated_count": 150,
            },
        }
        mock_response = create_mock_response(task_data, status=200)
        mocker.patch.object(api.api_client, "call_api", return_value=mock_response)

        task_id = "550e8400-e29b-41d4-a716-446655440000"
        result = api.get_task(id=task_id)

        assert result["task_type"] == "bulk_update"
        assert result["result"]["updated_count"] == 150
