"""
Ibutsu API

A system to store and query test results

The version of the OpenAPI document: 2.7.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from ibutsu_client.models.report_list import ReportList


class TestReportList(unittest.TestCase):
    """ReportList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportList:
        """Test ReportList
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReportList`
        """
        model = ReportList()
        if include_optional:
            return ReportList(
                reports = [
                    {"id":"a9560d7d-dbe4-4a7f-8d09-dde6b5b137ae","filename":"myreport.zip","mimetype":"application/zip","url":"http://ibutsu/reports/download/myreport.zip","download_url":"http://ibutsu/reports/download/myreport.zip","view_url":"http://ibutsu/reports/view/myreport.zip","parameters":{"type":"dashboard","filter":"test_navigation","source":"iqe-jenkins"},"status":"done"}
                    ],
                pagination = {"page":2,"pageSize":25,"totalPages":10,"totalItems":243}
            )
        else:
            return ReportList(
        )
        """

    def testReportList(self):
        """Test ReportList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
