"""
    Ibutsu API

    A system to store and query test results  # noqa: E501

    The version of the OpenAPI document: 2.2.1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "ibutsu-client"
VERSION = "2.2.2"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Ibutsu API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://github.com/ibutsu/ibutsu-client-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Ibutsu API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    A system to store and query test results  # noqa: E501
    """
)
